#! /bin/sh

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true' &
wmname LG3D &

bspc monitor DP-2 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X

bspc config border_width         3
bspc config borderless_monocle   false

bspc config window_gap            10
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

#bspc config focused_border_color "#BF616A"
#bspc config normal_border_color "#353b45"

# autostart up applications 
~/.config/polybar/launch.sh &
picom & 
feh --bg-fill $HOME/wallpapers/lighthouse.png &
xrdb merge ~/.Xresources &
sxhkd 
